### ISSUE TITLE
I3 SDK Cloud Instance Testing

### ISSUE THREAD

**Issue by summer7xinting** [ANRGUSC/I3-SDK#3]
### Tests
Used cloud instance at 34.219.145.25:1883. Tried to test local instance (localhost:1883) but the set up is buggy (still figuring out why).

### Problems

The documentation of I3 SDK is outdated and somehow incomplete. Took me quite a while to find the correct way to do things :(

1. test_sub/pub is written in Python 2.7(?) and requires paho-mqtt to be installed (see https://www.eclipse.org/paho/clients/python/docs/). I think we should specified that in either a README or a Pipfile.

2. The text documentation on all test_sub/pub scripts are somewhat misleading:
**On test_pub side:** 
    clientId = 'Default'    # clientId should be a unique string (assigned by broker, not user)
    account = 'Default'    # account should be a device registered under the same hub
    topic = ['Default']    # topic should be the topic to publish to
    pw = 'Default'    # pw should be the device API_key
    port = 1883
    host = 'Default' # host should be MQTT instance
**On test_sub side:**
    clientId = 'Default'    # clientId should be a unique string (assigned by broker)
    account = 'Default'    # account should be buyer user name
    topic = ['Default']    # topic should be the topic to subscribe to
    pw = 'Default'    # pw should be the generated password in notification center
    port = 1883
    host = 'Default' # host should be MQTT instance

I believe this is the correct (and up-to-date documentation): http://18.219.4.146:8000/media/I3_v1_user_guide.pdf

3. There is a tiny bug in all sub scripts:
`sub_client.subscribe(topic)` should be `sub_client.subscribe(topic[0])` if we keep topic as a list object. The idea should be to loop through all items in topic list and subscribe to all of them. This script now has a `ValueError: too many values to unpack`.

**Comment by summer7xinting** [comment]
Note from meeting:
1. version documentation should be tied to test scripts: update the text documentation as well
2. add more call back on mqtt client return code
![image](https://user-images.githubusercontent.com/18204249/65555751-4306b900-dee2-11e9-9e6a-87c371c02333.png)

**Comment by smcd253** [comment]
Fixed points 1 and 3 from original issue posting.

Closing this issue and will open a new issue on the documentation with @summer7xinting 's comments in point 2.
